### ISSUE TITLE
Archivado por trimestres

### ISSUE THREAD

**Issue by MarcoAurelioWM** [MarioFinale/PeriodiBOT#13]
Buenas. ¿Sería posible que el bot también archivase por trimestres? No veo dicha opción para [Plantilla:Archivado automático](https://es.wikipedia.org/wiki/Plantilla:Archivado_autom%C3%A1tico) y sería beneficioso para páginas como [CNU](https://es.wikipedia.org/wiki/Wikipedia:Cambiar_el_nombre_de_usuario) que, sin ser necesario un archivo mensual de peticiones, un único archivo anual sería igualmente poco práctico al excederse con creces el límite de transclusión de plantillas por el elevado número de solicitudes que se reciben en cómputo anual. Me temo que un archivo semestral sería igualmente demasiado grande. Muchas gracias. Un saludo.

**Comment by MarioFinale** [comment]
@MarcoAurelioWM  Añadido en 35085722b14dd46d8fa0398d201a500c0e2e335d.
También actualizada la plantilla en Wikipedia.
Saludos!

**Comment by MarcoAurelioWM** [comment]
Muchas gracias :) Saludos.
